from .exception import PyCEException


class PieceNotFoundError(PyCEException):
    pass
